spring.application.name=fashion-commerce-backend

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=fashion_ecommerce;encrypt=false;trustServerCertificate=true
spring.datasource.username=hieu
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

